config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks
  end
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'application#index', as: :authenticated_root
    end

    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    @city = request.location.city.presence || 'Reno, NV'
    # lat_lon = Geocoder.search(@city)[0].coordinates
    client = YahooWeather::Client.new
    @weather = client.fetch(2480201)
  end

  private

  def require_login
    unless current_user
      redirect_to unauthenticated_root_path
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end


  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  def set_project
    @project = Project.find(params[:id])
    @tasks = @project.tasks
  end

  def project_params
    params.require(:project).permit(:name, :horizon).merge(user_id: current_user.id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_login
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project, except: :show

  def index
    @tasks = @project.tasks
  end

  def show
  end

  def new
    @task = @project.tasks.new
  end

  def edit
  end

  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      redirect_to project_task_path(id: @task.id, project_id: @task.project_id), notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to project_path(@task.project_id), notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to project_path(@project.id), notice: 'Task was successfully destroyed.'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def set_project
    @project = @task ? @task.project : Project.find(params[:project_id])
  end

  def task_params
    params.require(:task).permit(:name, :complete).merge(user_id: current_user.id)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/application/index.html.erb
<span style='font-size:3em'><%= @weather.condition.temp %>&deg;</span><br />
<%= @city %>
<h1 style="text-align:center;display:inline"> Tellos </h1>
<div id='clock'style="display:inline;font-size:3em;float:right"></div>
<br />

<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "waves-effect waves-light btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tellos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'clock', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class='container'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tellos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.text_field :name, id: "project_name" %>
  <%= form.label :name, for: "project_name" %>
  <%= form.text_field :horizon, id: "project_horizon" %>
  <%= form.label :horizon, for: "project_horizon" %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.horizon %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @project.name %><span style="font-size: 0.5em">   [<%= @project.horizon %>]</span></h1>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Complete?</td>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.complete %></td>
        <td><%= link_to 'Show', project_task_path(@project.id, task.id) %></td>
        <td><%= link_to 'Edit', edit_project_task_path(@project.id, task.id) %></td>
        <td><%= link_to 'Destroy', project_task_path(@project.id, task.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_project_task_path(project_id: @project.id) %> |
<%= link_to 'Edit',  edit_project_task_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_with(model: [@project, @task]) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.text_field :name %>
  <%= form.check_box :complete, id: "task_complete" %>
  <%= form.label :complete, for: "task_complete" %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', project_task_path(@task.id) %> |
<%= link_to 'Back', project_tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @project.name %> Tasks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.complete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to Project', project_path(@project) %> |
<%= link_to 'New Task', new_project_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', project_tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @task.name %></h1>
<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Complete?</td>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @task.name %></td>
      <td><%= @task.complete %></td>
      <td><%= link_to 'Edit', edit_project_task_path(@task) %></td>
      <td><%= link_to 'Back', project_path(@task.project.id) %></td>
    </tr>
  </tbody>
</table>